name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test-and-build:
    name: Test and Build
    uses: imccausl/eslint-config/.github/workflows/test-and-build.yml@main

  publish:
    if: |
      github.event_name == 'push' &&
      github.ref_name == github.event.repository.default_branch
    needs: test-and-build
    uses: imccausl/eslint-config/.github/workflows/publish.yml@main
    secrets: inherit
