name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-build:
    name: Test and Build
    if: ${{ !contains('[skip_ci]', github.event.pull_request.title) }}
    uses: imccausl/eslint-config/.github/workflows/test-and-build.yml@main

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains('[skip_ci]', github.event.pull_request.title)
    needs: test-and-build
    uses: imccausl/eslint-config/.github/workflows/publish.yml@main
