name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-build:
    name: Test and Build
    if: |
      !contains('[skip_ci]', github.event.pull_request.title)
    uses: imccausl/eslint-config/.github/workflows/test-and-build.yml@main

  publish:
    if: |
      github.event_name == 'push' &&
      github.ref_name == github.event.repository.default_branch && 
      !contains('[skip_ci]', github.event.pull_request.title)
    needs: test-and-build
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: imccausl/eslint-config/.github/workflows/publish.yml@main
    secrets: inherit
