name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: ${{ !contains('[skip_ci]', github.event.pull_request.title) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Prepare Env
        uses: ./.github/actions/prepare-env@main

      - name: Cache build
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: lib
          key: ${{ runner.os }}-lib-${{ hashFiles('**/yarn.lock', '**/package.json', '**/src/**/*') }}

      - name: Build
        run: |
          yarn build
